/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import datos.gestionArchivo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author AdrianM
 */
public class jPanelImprimir extends javax.swing.JPanel {
    
    private ArrayList<clsCarro> lstCarros;
    private ArrayList<clsMoto> lstMotos;
    public jPanelImprimir(ArrayList<clsCarro> lstCarros,
            ArrayList<clsMoto> lstMotos) {
        this.lstCarros = lstCarros;
        this.lstMotos = lstMotos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCarros = new javax.swing.JTextPane();
        btnImprimirCarros = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotos = new javax.swing.JTextPane();
        btnImprimirMotos = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(txtCarros);

        btnImprimirCarros.setText("Imprimir carros");
        btnImprimirCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirCarrosActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane2.setViewportView(txtMotos);

        btnImprimirMotos.setText("Imprimir Motos");
        btnImprimirMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirMotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCentralLayout = new javax.swing.GroupLayout(jpCentral);
        jpCentral.setLayout(jpCentralLayout);
        jpCentralLayout.setHorizontalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(btnImprimirMotos, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jpCentralLayout.setVerticalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCentralLayout.createSequentialGroup()
                        .addComponent(btnImprimirMotos)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(jpCentralLayout.createSequentialGroup()
                        .addComponent(btnImprimirCarros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        add(jpCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirCarrosActionPerformed
        String resultado =  "";
        for(int i=0; i<this.lstCarros.size(); i++){
            resultado = resultado + 
                    this.lstCarros.get(i).obtenerInformacion();
        }
        this.txtCarros.setText(resultado);
    }//GEN-LAST:event_btnImprimirCarrosActionPerformed

    private void btnImprimirMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirMotosActionPerformed
        String resultado =  "";
        for(int i=0; i<this.lstMotos.size(); i++){
            resultado = resultado + 
                    this.lstMotos.get(i).obtenerInformacion();
        }
        this.txtMotos.setText(resultado);
    }//GEN-LAST:event_btnImprimirMotosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirCarros;
    private javax.swing.JButton btnImprimirMotos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpCentral;
    private javax.swing.JTextPane txtCarros;
    private javax.swing.JTextPane txtMotos;
    // End of variables declaration//GEN-END:variables
}
