/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.clsCarro;
import modelo.clsExcepcionRango;

/**
 *
 * @author AdrianM
 */
public class jPanelCarro extends javax.swing.JPanel {

    private ArrayList<clsCarro> lstCarros;
    
    public jPanelCarro(ArrayList<clsCarro> lstCarros) {
        this.lstCarros = lstCarros;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCentral = new javax.swing.JPanel();
        lblPropietario = new javax.swing.JLabel();
        lblRunt = new javax.swing.JLabel();
        lblPuertas = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        txtRunt = new javax.swing.JTextField();
        txtPuertas = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        setLayout(new java.awt.BorderLayout());

        lblPropietario.setText("Digite propietario:");

        lblRunt.setText("Digite Runt:");

        lblPuertas.setText("Digite # puertas:");

        lblMatricula.setText("Digite matricula:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCentralLayout = new javax.swing.GroupLayout(jpCentral);
        jpCentral.setLayout(jpCentralLayout);
        jpCentralLayout.setHorizontalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar)
                    .addGroup(jpCentralLayout.createSequentialGroup()
                        .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPropietario)
                            .addComponent(lblRunt)
                            .addComponent(lblPuertas)
                            .addComponent(lblMatricula))
                        .addGap(18, 18, 18)
                        .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPuertas)
                            .addComponent(txtPropietario)
                            .addComponent(txtRunt)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jpCentralLayout.setVerticalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpCentralLayout.createSequentialGroup()
                        .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPropietario)
                            .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRunt)
                            .addComponent(txtRunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblPuertas))
                    .addComponent(txtPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatricula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        add(jpCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void validarRango(long runt) throws clsExcepcionRango{
        if(runt < 10000 || runt > 10000000){
            throw new clsExcepcionRango ("Numero runt fuera de Rango");
        }
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        try{
            clsCarro objC = new clsCarro();
            objC.setPropietario(this.txtPropietario.getText());
            
            this.validarRango(Long.parseLong(this.txtRunt.getText()));
            objC.setRunt(Long.parseLong(this.txtRunt.getText()));
            
            objC.setMatricula(this.txtMatricula.getText());
            
            int puertas = Integer.parseInt(this.txtPuertas.getText());
            if(puertas >= 5){
                throw new Exception ("Numero de puertas invalido");
            }else{
                objC.setPuertas(puertas);
            }
        
            this.lstCarros.add(objC);

            JOptionPane.showMessageDialog(this,
                    "Registro exitoso de carro!!!",
                    "Guardar carro",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        catch(NumberFormatException e){
            //e.printStackTrace();   //Nos muestra los errores en la consola
            JOptionPane.showMessageDialog(this,
                "Error al ingresar datos numericos",
                "Validacion",
                JOptionPane.ERROR_MESSAGE);
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this,
                "No hay espacio para guardar datos",
                "Validacion",
                JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Error interno en el Programa "+e.getMessage(),
                "Validacion",
                JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.txtPropietario.setText("");
            this.txtRunt.setText("");
            this.txtMatricula.setText("");
            this.txtPuertas.setText("");
        }
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jpCentral;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblPuertas;
    private javax.swing.JLabel lblRunt;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtPuertas;
    private javax.swing.JTextField txtRunt;
    // End of variables declaration//GEN-END:variables
}
