/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.clsCarro;
import modelo.clsMoto;
import modelo.enumMoto;

/**
 *
 * @author AdrianM
 */
public class jPanelMoto extends javax.swing.JPanel {

    private ArrayList<clsMoto> lstMotos;
    
    public jPanelMoto(ArrayList<clsMoto> lstMotos) {
        this.lstMotos = lstMotos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCentral = new javax.swing.JPanel();
        lblPropietario = new javax.swing.JLabel();
        lblRunt = new javax.swing.JLabel();
        lblCilindraje = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        txtRunt = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        lblPropietario.setText("Digite propietario:");

        lblRunt.setText("Digite runt:");

        lblCilindraje.setText("Digite Cilindraje:");

        lblTipo.setText("Digite tipo:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasica", "Deportiva", "CicloMotores", "Scooter", "Trail" }));

        javax.swing.GroupLayout jpCentralLayout = new javax.swing.GroupLayout(jpCentral);
        jpCentral.setLayout(jpCentralLayout);
        jpCentralLayout.setHorizontalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar)
                    .addGroup(jpCentralLayout.createSequentialGroup()
                        .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCentralLayout.createSequentialGroup()
                                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPropietario)
                                    .addComponent(lblRunt)
                                    .addComponent(lblCilindraje))
                                .addGap(30, 30, 30))
                            .addGroup(jpCentralLayout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCilindraje, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtRunt, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jpCentralLayout.setVerticalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropietario)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunt)
                    .addComponent(txtRunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCilindraje)
                    .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        add(jpCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        clsMoto objM = new clsMoto();
        objM.setPropietario(this.txtPropietario.getText());
        objM.setRunt(Long.parseLong(this.txtRunt.getText()));
        objM.setCilindraje(Integer.parseInt(this.txtCilindraje.getText()));
       
        int index = this.cmbTipo.getSelectedIndex();
        enumMoto aux;
        switch(index){
            case 0:
                aux = enumMoto.Clasica;
                break;
            case 1:
                aux = enumMoto.Deportiva;
                break;
            case 2:
                aux = enumMoto.CicloMotores;
                break;
            case 3:
                aux = enumMoto.Scooter;
                break;
            case 4:
                aux = enumMoto.Trail;
                break;
            default:
                aux = null;
        }
        objM.setTipo(aux);
               
        this.lstMotos.add(objM);
        
        JOptionPane.showMessageDialog(this,
                "Registro exitoso de moto!!!",
                "Guardar moto",
                JOptionPane.INFORMATION_MESSAGE);
        
        this.txtPropietario.setText("");
        this.txtRunt.setText("");
        this.txtCilindraje.setText("");
        this.cmbTipo.setSelectedIndex(0);
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JPanel jpCentral;
    private javax.swing.JLabel lblCilindraje;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblRunt;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtRunt;
    // End of variables declaration//GEN-END:variables
}
