package vista;

import datos.gestionArchivo;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author AdrianM
 */
public class vtnPrincipal extends javax.swing.JFrame {

    private jPanelCarro jpCarro;
    private jPanelMoto jpMoto;
    private jPanelImprimir jpImprimir;
    private ArrayList<clsCarro> lstCarros;
    private ArrayList<clsMoto> lstMotos;
    
    public vtnPrincipal(ArrayList<clsCarro> lstCarros,ArrayList<clsMoto> lstMotos) {
        this.lstCarros = lstCarros;
        this.lstMotos = lstMotos;
        
        this.jpCarro = new jPanelCarro(lstCarros);
        this.jpMoto = new jPanelMoto(lstMotos);
        this.jpImprimir = new jPanelImprimir(this.lstCarros,lstMotos);
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }
    
    private void eventCerrar(){
        String botones [] = {"Si, Salir","No, Salir"};
        int eleccion = JOptionPane.showOptionDialog(this, 
                "¿Desea Guardar los Datos Registrados y Salir?", 
                "Validación de Cierre", 0, 0, null, botones, this);
        if(eleccion==JOptionPane.YES_OPTION){
            gestionArchivo GA = new gestionArchivo();
            GA.escribirDatosVehiculo(this.lstCarros);
        
            JOptionPane.showMessageDialog(this,
                    "Datos Guardados con Éxito",
                    "Gestion Escritura",
                    JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }else if(eleccion==JOptionPane.NO_OPTION){
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jpIzquierda = new javax.swing.JPanel();
        btnCarro = new javax.swing.JButton();
        btnMoto = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jpCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitulo.setText("GESTIÓN DE VEHICULOS");
        jpSuperior.add(lblTitulo);

        getContentPane().add(jpSuperior, java.awt.BorderLayout.PAGE_START);

        jpIzquierda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCarro.setText("Crear Carro");
        btnCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroActionPerformed(evt);
            }
        });

        btnMoto.setText("Crear Moto");
        btnMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIzquierdaLayout = new javax.swing.GroupLayout(jpIzquierda);
        jpIzquierda.setLayout(jpIzquierdaLayout);
        jpIzquierdaLayout.setHorizontalGroup(
            jpIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIzquierdaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarro)
                    .addGroup(jpIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpIzquierdaLayout.setVerticalGroup(
            jpIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIzquierdaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnCarro)
                .addGap(18, 18, 18)
                .addComponent(btnMoto)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        getContentPane().add(jpIzquierda, java.awt.BorderLayout.LINE_START);

        jpCentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpCentral.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jpCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroActionPerformed
        this.jpCentral.remove(this.jpMoto);
        this.jpCentral.remove(this.jpImprimir);
        this.jpCentral.add(this.jpCarro,BorderLayout.CENTER);
        this.jpCentral.revalidate();
        this.jpCentral.repaint();
    }//GEN-LAST:event_btnCarroActionPerformed

    private void btnMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoActionPerformed
        this.jpCentral.remove(this.jpCarro);
        this.jpCentral.remove(this.jpImprimir);
        this.jpCentral.add(this.jpMoto,BorderLayout.CENTER);
        this.jpCentral.revalidate();
        this.jpCentral.repaint();
    }//GEN-LAST:event_btnMotoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
         this.jpCentral.remove(this.jpCarro);
        this.jpCentral.remove(this.jpMoto);
        this.jpCentral.add(this.jpImprimir,BorderLayout.CENTER);
        this.jpCentral.revalidate();
        this.jpCentral.repaint();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        eventCerrar();
    }//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarro;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMoto;
    private javax.swing.JPanel jpCentral;
    private javax.swing.JPanel jpIzquierda;
    private javax.swing.JPanel jpSuperior;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
